/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ChartView: typeof import('./src/components/chart/ChartView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineCharts: typeof import('./src/components/LineCharts.vue')['default']
  }
}
